### ISSUE TITLE
Trying to retrieve forgotten password result in error screen

### ISSUE THREAD

**Issue by nexusstar** [NikolayIT/OpenJudgeSystem#505]
When I try to retrieve forgotten password it result in following error:
```
   System.Net.Mail.SmtpException: Cannot get IIS pickup directory.
   at System.Net.Mail.IisPickupDirectory.GetPickupDirectory()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at OJS.Web.Controllers.AccountController.SendForgottenPasswordToUser(UserProfile user)
   at OJS.Web.Controllers.AccountController.ForgottenPassword(String emailOrUsername)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```

**Comment by Y-LyN-10** [comment]
+1
I've got the same error and I can't restore my password.  
Is it expected that this bug will be fixed in the next release?
